language: node_js
node_js:
  - node
  
branches:
  only:
    - master

before_script:
  - chmod +x travis-ci.sh
  - npm install -g gulp-cli

deploy:
  - provider: script
    script: deploy.sh ./app gh-pages https://$GITHUB_TOKEN@github.com/jessevdp/web.git
    on:
      branch: master
