language: node_js
node_js:
  - node

branches:
  only:
    - master

before_script:
  - chmod +x travis-ci.sh
  - npm install -g gulp-cli

deploy:
  - provider: script
    skip_cleanup: true
    script: gulp deploy
    on:
      branch: master
